---
driver:
  name: ec2
  aws_ssh_key_id: coupa
  region: us-east-1
  availability_zone: d
  subnet_id: subnet-b0f8b69a
  instance_type: t2.micro
  image_id: ami-aa2ea6d0
  security_group_ids: ["sg-19512a6c"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /opt/keys/coupa.pem

platforms:
  - name: ubuntu-16.04

suites:
  - name: default 
    data_bags_path: 'test/smoke/data_bags'
    run_list:
      - recipe[ror-app::default]
    verifier:
      inspec_tests:
        - test/smoke/default/integration_test.rb
        - test/smoke/default/compliance_test.rb
